### ISSUE TITLE
cli: add CLI command which updates the SECRET_KEY

### ISSUE THREAD

**Issue by nharraud** [inveniosoftware/invenio-base#105]
**Problem:**
It should be possible to update the SECRET_KEY if it is compromized.

Design TBD

**Comment by jirikuncar** [comment]
@nharraud you might need then to rebuild all encrypted columns in DB (tokens, passwords, etc.)

**Comment by nharraud** [comment]
@jirikuncar Yes that's what @lnielsen told me too.

One design (suggested by Lars) would be to just send a signal with the previous secret and the new one. Each module using it would be in charge or decrypting, reencrypting the columns.

**Comment by dinosk** [comment]
I noted the following parts that will be affected by changing the SECRET_KEY:

- invenio-accounts:  the SECRET_KEY will be used as the [SECURITY_PASSWORD_SALT](https://github.com/inveniosoftware/invenio-accounts/blob/master/invenio_accounts/ext.py#L187) if it is not set. When the SECRET_KEY is updated it is possible to keep the salt by setting SECURITY_PASSWORD_SALT to the previous value of SECRET_KEY. Although by default the hashing algorithm is set to [pbkdf2_sha512](https://github.com/inveniosoftware/invenio-accounts/blob/master/invenio_accounts/config.py#L68) which doesn't [seem to use it](https://passlib.readthedocs.io/en/stable/lib/passlib.hash.pbkdf2_digest.html#passlib.hash.pbkdf2_sha256), and the login after the change worked.
- invenio-oauthclient: used for encrypting the access_token in the [RemoteToken](https://github.com/inveniosoftware/invenio-oauthclient/blob/master/invenio_oauthclient/models.py#L139) table. This [PR](https://github.com/inveniosoftware/invenio-oauthclient/pull/126) is a first attempt to add the receiver for the signal from [invenio-base](https://github.com/inveniosoftware/invenio-base/pull/107) that rebuilds the access_token field. This part affects the login of the users after the change, without rebuilding the access_tokens there is a decoding error when decryption with the old secret key is attempted.
- invenio-oauth2server: same thing for the [Token](https://github.com/inveniosoftware/invenio-oauth2server/blob/master/invenio_oauth2server/models.py#L340) table. This [PR](https://github.com/inveniosoftware/invenio-oauth2server/pull/110) does the same. One of the affected parts is the REST api, the changes allow the users to keep their access tokens.

For the flask modules (used in invenio-app-ils):
- Flask-KVSession: the cookie signature will not match once the SECRET_KEY is changed. Thus users who where logged in will be logged out.
- Flask-WTF: the SECRET_KEY is used as the CSRF token for the view forms when [WTF_CSRF_SECRET_KEY](https://github.com/lepture/flask-wtf/blob/master/flask_wtf/csrf.py#L33) is not set. When the SECRET_KEY is changed the forms which were sent to users’ browsers before the update cannot be submitted. Simply reloading the page would fix the issue. Otherwise it would also be possible to set WTF_CSRF_SECRET_KEY with the previous SECRET_KEY.
- Flask-Login: uses it to sign [cookies](https://github.com/maxcountryman/flask-login/blob/master/flask_login/utils.py#L318), so the cookies won't be recognised.

**Comment by lnielsen** [comment]
One thing to add to the list is the zenodo/zenodo-accessrequests module (which of course is for zenodo only currently but B2SHARE had intentions to use).

**Comment by nharraud** [comment]
@lnielsen yes we should take care of this one too at the same time so that we don't forget to do it later.
@dinosk

**Comment by lnielsen** [comment]
Closed by #107
