### ISSUE TITLE
cli: add `instance create` command

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-base#28]
This task should be built on top of PR #27 (which we can hopefully integrate later today)

Add a command ``startproject`` (name TBC) to ``inveniomanage`` that will generate an initial project structure using cookiecutter

Example of usage:
```inveniomanage startproject mysite```

will generate something a project structure like this:
https://github.com/lnielsen/mysite

The project structure should be generated using [cookiecutter Pythonic API](https://cookiecutter.readthedocs.org/en/latest/advanced_usage.html#calling-cookiecutter-functions-from-python). 

The cookiecutter template should be included in invenio-base and full path to found using ``pkg_resources``.

**Comment by lnielsen** [comment]
Ping @tiborsimko: What do we do with the naming here:

```
inveniomanage projects start
inveniomanage instances create
inveniomanage overlay start
```
?

**Comment by tiborsimko** [comment]
Hmm, I guess `startproject` may remind people too much of Django.  

- In Django, such a name is OK, because people can do very many projects of vary diverse topics and nature. So starting a "project" makes perfect sense.

- In Invenio, there is already an underlying common theme, the digital repository of sorts, which kind of restricts the "projects" people are looking for.  Hence creating an "instance" or a "site" or an "overlay" may be better suited here indeed.  

FWIW I prefer "create" (rather than "start"), and a singular "instance" or "overlay" (rather than "project" or "site").   

Let's try to finalise the terminology ASAP so that it is ready for Monday?

**Comment by jirikuncar** [comment]
My votes for:
- object: `instance`, `overlay`
- verb: `create`

hence: `inveniomanage instance create [name]`

--
For bright future of: `inveniomanage instance check --requirements [dir_name]`, `inveniomanage instance update --requirements [dir_name]`

**Comment by lnielsen** [comment]
:+1: for ``instance``

Overlay reminds me too much of Invenio legacy with overwrite files :-)

**Comment by tiborsimko** [comment]
We all seem to agree then.  I've changed the ticket issue title consequently.

**Comment by lnielsen** [comment]
@JavierDelgadoFernandez Do you think it's possible to have this change ready for later today, so that it can be included in the demo on monday?

**Comment by JavierDelgadoFernandez** [comment]
@lnielsen Ok, I am starting now.

**Comment by lnielsen** [comment]
Great, thanks a lot.
